name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read; write
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
    - run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Setup Node.js environment
  uses: actions/setup-node@v5.0.01

